### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by thaddeusm** [AyoubElk/grammarbot#1]
I cannot return a response from the GrammarBot API (either using this library or a standard Ajax request) from a client in the browser due to CORS errors:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://api.grammarbot.io/v2/check?api_key=AF5B9M2X&text=This%is%a%20tst.. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by AyoubElk** [comment]
This is the error I'm getting when clicking that url: 
![image](https://user-images.githubusercontent.com/11050534/61364917-a2ab6d00-a87e-11e9-8cfe-9d9390feb496.png)
And it has to do with the text provided, it isn't correctly formated: 
- A url encoded space character is `%20` not `%`

![image](https://user-images.githubusercontent.com/11050534/61365012-d9818300-a87e-11e9-9ab7-112d973300be.png)

If you're really facing a CORS issue like you mentioned, can you share more details?

**Comment by thaddeusm** [comment]
Sorry, I had formatting errors in my example.  When trying "http://api.grammarbot.io/v2/check?api_key=AF5B9M2X&text=This%20is%20a%20tst" through CURL everything looks fine.  

I tried implementing the Grammarbot library as well but I am still receiving text formatting errors.  Is it possible to pass in an unformatted string as a parameter in the bot.check() method?  Should I remove/replace white spaces first?  The example provided in the documentation seems to suggest that  a plain string would work.

**Comment by AyoubElk** [comment]
Yes a plain string should work, please provide a code sample and its output so I can debug the problem with you.

**Comment by thaddeusm** [comment]
Here is the server function implementation I am working on:

```
const { send } = require('micro')
const cors = require('micro-cors')()

const Grammarbot = require('grammarbot')
const key = process.env.GRAMMARBOT_KEY

const bot = new Grammarbot({
	'api_key': key,
	'language': 'en-US',
  	'base_uri': 'api.grammarbot.io'
})

const handler = (req, res) => {
	if (req.method === 'OPTIONS') {
		return send(res, 200, 'ok!')
	}


	if (req.method !== 'POST') {
		throw createError(404, 'Not Found')
	}

	console.log(req.body.textContent)

	bot.check(req.body.textContent, function(error, result) {
		if (error) {
			result = error
			throw createError(402, 'Error')
		} else {
			result = JSON.stringify(result)
			return send(res, 200, result)
		}
	})

	
}

module.exports = cors(handler)
```
This is the output returned after sending a post request with a text string as the "textContent":

`{"timestamp":"2019-07-18T04:11:11.787+0000","status":400,"error":"Bad Request","message":"Required String parameter 'text' is not present","path":"/v2/check"}`

**Comment by AyoubElk** [comment]
Thanks @thaddeusm
Looks like there is something changed at the API level, the example in the documentation doesn't work anymore as well.
Will check later during the day.

**Comment by thaddeusm** [comment]
@AyoubElk Thank you for looking into this.  I am looking forward to using this API.

**Comment by FatJoe-Ryan** [comment]
I've been trying to use this today and I'm getting the same issue.

**Comment by AyoubElk** [comment]
I just pushed a fix.

I'll close this issue, feel free to re-open it if needed.
