### ISSUE TITLE
Issue with GrammerBot API with node js

### ISSUE THREAD

**Issue by tushar2197** [AyoubElk/grammarbot#3]
I have use node.js platform and integrate grammar-bot API but when i send request using Async/Await style or Callback style but it will return  
       {"timestamp": "2019-10-10T10:20:38.301+0000",
        "status": 400,
        "error": "Bad Request",
        "message": "Required String parameter 'text' is not present",
        "path": "/v2/check"
}
every time . So, please help me to find solution for this.

**Comment by wallawe** [comment]
@AyoubElk If no one is going to address issues, it would be helpful to add a notice that it's not currently maintained in the readme so that no one spends time installing this package only to come back and find that it doesn't work.

**Comment by AyoubElk** [comment]
Thanks for the mention @wallawe, I somehow missed this issue.

Will take a look and provide a fix in a few hours.

**Comment by wallawe** [comment]
Thanks for following up @AyoubElk. Not sure if it helps, but here's how I ended up rewriting the class: 

```
const axios = require('axios')

const BASE_URI = 'http://api.grammarbot.io'

class GrammarBot {
  constructor(config) {
    this.base_uri = config.base_uri || BASE_URI
    this.language = config.language || 'en-US'
    this.api_key = config.api_key || 'node-default'
  }

  check(text, done) {
    const reqParams = {
      language: this.language,
      'api-key': this.api_key,
      text: text,
    }

    const options = {
      url: this.base_uri + '/v2/check',
      method: 'POST',
      headers: {},
      params: reqParams,
    }

    return axios.request(options)
  }
}
```

**Comment by AyoubElk** [comment]
Thanks for the help @wallawe. I just deployed a fix.
